run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - gocognit # allow higher cognitive complexity
    - testpackage # unwanted convention
    - nestif # allow deep nesting
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - maligned # pre-optimization
    - nlreturn # don't enforce blank line before return
    - exhaustive # don't enforce exhaustive switches
    - exhaustivestruct # don't require specifying all struct fields
    - errorlint # TODO: consider updating to %w and enabling
    - wrapcheck # TODO: consider adding error wrapping and enabling
    - forbidigo # Printf allowed in example tests
