/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TimeRestictedWeekdays the model 'TimeRestictedWeekdays'
type TimeRestictedWeekdays string

// List of TimeRestictedWeekdays
const (
	TIMERESTICTEDWEEKDAYS_MO TimeRestictedWeekdays = "mo"
	TIMERESTICTEDWEEKDAYS_TU TimeRestictedWeekdays = "tu"
	TIMERESTICTEDWEEKDAYS_WE TimeRestictedWeekdays = "we"
	TIMERESTICTEDWEEKDAYS_TH TimeRestictedWeekdays = "th"
	TIMERESTICTEDWEEKDAYS_FR TimeRestictedWeekdays = "fr"
	TIMERESTICTEDWEEKDAYS_SA TimeRestictedWeekdays = "sa"
	TIMERESTICTEDWEEKDAYS_SU TimeRestictedWeekdays = "su"
)
