/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// RoutingMode Specifies which optimization is applied during route calculation.  * `fast`: Route calculation from start to destination optimized by travel time. In many   cases, the route returned by the `fast` mode may not be the route with the fastest   possible travel time. For example, the routing service may favor a route that remains on   a highway, even if a faster travel time can be achieved by taking a detour or shortcut   through an inconvenient side road. * `short`: Route calculation from start to destination disregarding any speed information.   In this mode, the distance of the route is minimized, while keeping the route sensible.   This includes, for example, penalizing turns. Because of that, the resulting route will   not necessarily be the one with minimal distance. 
type RoutingMode string

// List of RoutingMode
const (
	ROUTINGMODE_FAST RoutingMode = "fast"
	ROUTINGMODE_SHORT RoutingMode = "short"
)
