/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// AttributionLinkType Attribution link type.  * `disclaimer` - Page with further legal information from the agency. * `tariff` - Page with information on the tariff. 
type AttributionLinkType string

// List of AttributionLinkType
const (
	ATTRIBUTIONLINKTYPE_DISCLAIMER AttributionLinkType = "disclaimer"
	ATTRIBUTIONLINKTYPE_TARIFF AttributionLinkType = "tariff"
)
