/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Fare `Fare` type contains information about a single fare or ticket needed for this section of the route.
type Fare struct {
	// Unique Fare id. Used to deduplicate fares that apply to multiple sections
	Id string `json:"id"`
	// Name of a fare
	Name string `json:"name"`
	Price FarePrice `json:"price"`
	// Extensible enum: `ride` `parking` `...`   Reason for the cost described in this `Fare` element. 
	Reason string `json:"reason,omitempty"`
}
