/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
import (
	"time"
)
// TransitDeparture Transit departure
type TransitDeparture struct {
	// Expected time of the departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.
	Time time.Time `json:"time,omitempty"`
	// Departure/arrival location
	Place StationPlace `json:"place"`
	// The accumulated delay in seconds from the scheduled time of the event.
	Delay int32 `json:"delay,omitempty"`
	// Extensible enum: `scheduled` `cancelled` `...`   Status of the departure 
	Status string `json:"status,omitempty"`
}
