/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TransitStop A transit stop of the route
type TransitStop struct {
	Departure TransitDeparture `json:"departure"`
	// Stop duration. If not set the vehicle departs as soon as people are on board.
	Duration int32 `json:"duration,omitempty"`
}
