/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// RouterRoute A basic route. Includes personal vehicles as car, truck, etc... For all modes, cf. `transportMode`. 
type RouterRoute struct {
	// Unique identifier of the route
	Id string `json:"id"`
	// Contains a list of issues encountered during the processing of this response.
	Notices []Notice `json:"notices,omitempty"`
	// An ordered list of vehicle, transit, and pedestrian sections making up the route. 
	Sections []RouterSection `json:"sections"`
	// Opaque handle of the calculated route.  A handle encodes the calculated route. The route can be decoded from a handle at a later point in time as long as the service uses the same map data which was used during encoding.  To request a handle set the `routeHandle` flag in `return` parameter. If a handle is requested, but fails to be calculated for any reason, then the `handle` property is not available in the response. The rest of the route is intact. 
	Handle string `json:"handle,omitempty"`
}
