// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Attribution The URL address to an external resource.
type Attribution struct {
	// Unique identifier for the web link. It is used to deduplicate links defined in multiple sections.
	Id string `json:"id"`
	// An URL address that links to a particular resource.
	Href string `json:"href,omitempty"`
	// Text describing the url address (e.g. The example website).
	Text string `json:"text"`
	// The interactive (or clickable) portion of the text. If not present (default), the entire content of the text attribute will be considered. 
	HrefText string `json:"hrefText,omitempty"`
	Type AttributionLinkType `json:"type,omitempty"`
}
