/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Spans the model 'Spans'
type Spans string

// List of Spans
const (
	SPANS_WALK_ATTRIBUTES Spans = "walkAttributes"
	SPANS_STREET_ATTRIBUTES Spans = "streetAttributes"
	SPANS_CAR_ATTRIBUTES Spans = "carAttributes"
	SPANS_TRUCK_ATTRIBUTES Spans = "truckAttributes"
	SPANS_NAMES Spans = "names"
	SPANS_LENGTH Spans = "length"
	SPANS_DURATION Spans = "duration"
	SPANS_BASE_DURATION Spans = "baseDuration"
	SPANS_COUNTRY_CODE Spans = "countryCode"
	SPANS_FUNCTIONAL_CLASS Spans = "functionalClass"
	SPANS_ROUTE_NUMBERS Spans = "routeNumbers"
	SPANS_SPEED_LIMIT Spans = "speedLimit"
	SPANS_DYNAMIC_SPEED_INFO Spans = "dynamicSpeedInfo"
	SPANS_SEGMENT_ID Spans = "segmentId"
	SPANS_CONSUMPTION Spans = "consumption"
)
