// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// VersionResponse Returns the versions of components of the service
type VersionResponse struct {
	// The current version of the API
	ApiVersion string `json:"apiVersion"`
	// The current version of the service
	ServiceVersion string `json:"serviceVersion,omitempty"`
	// Returns the versions of data sets used by the service
	DataVersions []DataVersion `json:"dataVersions,omitempty"`
}
