/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Return Defines which attributes are included in the response as part of data representation of a `Route` or `Section`.  * `polyline` - Polyline for the route in [Flexible Polyline](https://github.com/heremaps/flexible-polyline) Encoding. * `actions` - Actions (such as maneuvers or tasks) that must be taken to complete the section. * `instructions` - Include instructions in included actions. * `summary` - Include summary for the section. * `travelSummary` - Include summary for the travel portion of the section. * `turnByTurnActions` - Include all information necessary to support turn by turn guidance to complete the section. * `elevation` - Include elevation information in coordinate and geometry types. See e.g. `polyline` or `location` * `routeHandle` - Encode calculated route and return a handle which can be used with   `routes/{routeHandle}` to decode the route at a later point in time. 
type Return string

// List of Return
const (
	RETURN_POLYLINE Return = "polyline"
	RETURN_ACTIONS Return = "actions"
	RETURN_INSTRUCTIONS Return = "instructions"
	RETURN_SUMMARY Return = "summary"
	RETURN_TRAVEL_SUMMARY Return = "travelSummary"
	RETURN_TURN_BY_TURN_ACTIONS Return = "turnByTurnActions"
	RETURN_ELEVATION Return = "elevation"
	RETURN_ROUTE_HANDLE Return = "routeHandle"
)
