/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// VehiclePostAction Action attached to a vehicle section that must be done after `arrival`.
type VehiclePostAction struct {
	// The type of the action.  **NOTE:** The list of possible actions may be extended in the future. The client application should handle such a case gracefully. 
	Action string `json:"action"`
	// Estimated duration of this action. Actions last until the next action, or the end of the route in case of the last one.
	Duration int32 `json:"duration"`
	// Description of the action (e.g. Turn left onto Minna St.).
	Instruction string `json:"instruction,omitempty"`
	// Maximum charging power (in kW) available to the vehicle, based on the properties of the charging station and the vehicle. 
	ConsumablePower float32 `json:"consumablePower,omitempty"`
	// Estimated vehicle battery charge before this action (in kWh). 
	ArrivalCharge float32 `json:"arrivalCharge,omitempty"`
	// Level to which vehicle battery should be charged by this action (in kWh). 
	TargetCharge float32 `json:"targetCharge,omitempty"`
	// Offset of a coordinate in the section's polyline.
	Offset int32 `json:"offset,omitempty"`
	// Attributes of the current road
	CurrentRoad RoadInfo `json:"currentRoad,omitempty"`
	// Attributes of the next road
	NextRoad RoadInfo `json:"nextRoad,omitempty"`
}
