/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TimeRestrictedPrice struct for TimeRestrictedPrice
type TimeRestrictedPrice struct {
	// Type of price represented by this object. The API customer is responsible for correctly visualizing the pricing model. As it is possible to extend the supported price types in the future, the price information should be hidden when an unknown type is encountered.  Available price types are:    * `restricted` - A single price value valid for a specific time or duration 
	Type string `json:"type"`
	// Attribute value is `true` if the fare price is estimated, `false` if it is an exact value.
	Estimated bool `json:"estimated,omitempty"`
	// Local currency of the price compliant to ISO 4217
	Currency string `json:"currency"`
	// When set, the price is paid for a specific duration.  Examples:   * `\"unit\": 3600` - price for one hour   * `\"unit\": 28800` - price for 8 hours   * `\"unit\": 86400` - price for one day 
	Unit int32 `json:"unit,omitempty"`
	// The price value
	Value float32 `json:"value"`
	// This price applies only for the selected days
	Days []TimeRestictedWeekdays `json:"days,omitempty"`
	// The price applies if the duration is more or equal to `minDuration`
	MinDuration int32 `json:"minDuration,omitempty"`
	// The price applies if the duration is less or equal to `maxDuration`
	MaxDuration int32 `json:"maxDuration,omitempty"`
	// The price applies from this time of the day
	FromTime string `json:"fromTime,omitempty"`
	// The price applies untill this time of the day
	ToTime string `json:"toTime,omitempty"`
}
