/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// RouteResponseNotice A notice contains important notifications.
type RouteResponseNotice struct {
	// Human readable notice description.
	Title string `json:"title,omitempty"`
	// Notice code.
	Code string `json:"code"`
	// Additional details about the notice
	Details []RouteResponseNoticeDetail `json:"details,omitempty"`
}
