// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// LocalizedString String with optional language code.
type LocalizedString struct {
	// String written in the language specified in the language property.
	Value string `json:"value"`
	// Language in BCP47 format
	Language string `json:"language,omitempty"`
}
