// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Exclude Options to exclude strictly during the route calculation.
type Exclude struct {
	// A comma separated list of three-letter country codes (ISO-3166-1 alpha-3 code) that routes will exclude. 
	Countries string `json:"countries,omitempty"`
}
