// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TurnActionDirection Direction of the turn. `middle` is only used by the `keep` action.
type TurnActionDirection string

// List of TurnActionDirection
const (
	TURNACTIONDIRECTION_MIDDLE TurnActionDirection = "middle"
	TURNACTIONDIRECTION_RIGHT TurnActionDirection = "right"
	TURNACTIONDIRECTION_LEFT TurnActionDirection = "left"
)
