// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Truck Truck parameters to be used during truck route calculation.
type Truck struct {
	// Comma-separated list of shipped hazardous goods in the vehicle.  Possible values are:  * `explosive`: Explosive material * `gas`: Gas * `flammable`: Flammable material * `combustible`: Combustible material * `organic`: Organic material * `poison`: Poison * `radioactive`: Radioactive material * `corrosive`: Corrosive material * `poisonousInhalation`: Materials that are poisonous upon inhalation * `harmfulToWater`: Materials that are harmful to water * `other`: Other types of hazardous materials 
	ShippedHazardousGoods string `json:"shippedHazardousGoods,omitempty"`
	// Vehicle weight including trailers and shipped goods, in kilograms.
	GrossWeight int32 `json:"grossWeight,omitempty"`
	// Vehicle weight per axle, in kilograms.
	WeightPerAxle int32 `json:"weightPerAxle,omitempty"`
	// Vehicle height, in centimeters.
	Height int32 `json:"height,omitempty"`
	// Vehicle width, in centimeters.
	Width int32 `json:"width,omitempty"`
	// Vehicle length, in centimeters.
	Length int32 `json:"length,omitempty"`
	TunnelCategory TunnelCategory `json:"tunnelCategory,omitempty"`
	// Defines total number of axles in the vehicle. 
	AxleCount int32 `json:"axleCount,omitempty"`
}
