// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
import (
	"time"
)
// PedestrianDeparture Departure of pedestrian
type PedestrianDeparture struct {
	// Expected time of the departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.
	Time time.Time `json:"time,omitempty"`
	Place PedestrianPlace `json:"place"`
}
