/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TurnActionSeverity Tightness of the turn. Optional in the `turn` action, unused by other actions.  * `light`: indicates making a light turn * `quite`: indicates making a regular turn * `heavy`: indicates making a heavy turn 
type TurnActionSeverity string

// List of TurnActionSeverity
const (
	TURNACTIONSEVERITY_LIGHT TurnActionSeverity = "light"
	TURNACTIONSEVERITY_QUITE TurnActionSeverity = "quite"
	TURNACTIONSEVERITY_HEAVY TurnActionSeverity = "heavy"
)
