// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Vehicle **Disclaimer: these parameters are work in progress and functionality is not complete**  Additional generic details about the vehicle for which the route is calculated.  Currently, only `hovOccupancy` is defined, with limited functionality 
type Vehicle struct {
	// Number of occupants (defined as occupying a restraint device) in the vehicle. This value affects the ability of the router to use HOV (High-Occupancy Vehicles) restricted lanes.  Limitations:   * only valid for `transportMode=car`.   * currently, any value over 1 is interpreted as being able to use any HOV lane (including, e.g. those restricted to 3+ passengers). 
	HovOccupancy int32 `json:"hovOccupancy,omitempty"`
}
