/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TruckAxleCountRange Constrains the restriction to trucks with number of axles within specified range.
type TruckAxleCountRange struct {
	// Inclusive minimum of axle count.
	From int32 `json:"from,omitempty"`
	// Inclusive maximum of axle count. If not set, maximum axle count is unbounded.
	To int32 `json:"to,omitempty"`
}
