// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// VehicleSummary Total value of key attributes for a route section.
type VehicleSummary struct {
	// Duration in seconds
	Duration int32 `json:"duration"`
	// Distance in meters
	Length int32 `json:"length"`
	// Energy in kilowatt hours (kWh)
	Consumption float32 `json:"consumption,omitempty"`
	// Duration (in seconds) ignoring time-aware information.  In particular, dynamic traffic information is not taken into account. Only free-flow speeds based on historical traffic are used to calculate this duration.  The `baseDuration` can also be understood as the best possible duration. 
	BaseDuration int32 `json:"baseDuration,omitempty"`
}
