// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// RoadInfo Road information attached to an offset action
type RoadInfo struct {
	Type RoadInfoType `json:"type,omitempty"`
	// Name of the road
	Name []LocalizedString `json:"name,omitempty"`
	// Route name or number (e.g. 'M25')
	Number []LocalizedString `json:"number,omitempty"`
}
