/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// VehicleSection Represent a section of a route
type VehicleSection struct {
	// Unique identifier of the section
	Id string `json:"id"`
	// Section type used by the client to identify what extension to the BaseSection are available.
	Type string `json:"type"`
	// Actions that must be done prior to `departure`.
	PreActions []BaseAction `json:"preActions,omitempty"`
	// Actions to be performed at or during a specific portion of a section.  Action offsets are the coordinate index in the polyline. 
	Actions []VehicleAction `json:"actions,omitempty"`
	// Language of the localized strings in the section, if any, in BCP47 format.
	Language string `json:"language,omitempty"`
	// Actions that must be done after `arrival`.
	PostActions []VehiclePostAction `json:"postActions,omitempty"`
	// Actions for turn by turn guidance.  Action offsets are the coordinate index in the polyline. 
	TurnByTurnActions []VehicleAction `json:"turnByTurnActions,omitempty"`
	Departure VehicleDeparture `json:"departure"`
	Arrival VehicleDeparture `json:"arrival"`
	// Total value of key attributes (e.g., duration, length) summed up for the entire section, including `preActions`, `postActions`, and the travel portion of the section. 
	Summary VehicleSummary `json:"summary,omitempty"`
	// Total value of key attributes (e.g., duration, length) summed up for just the travel portion of the section, between `departure` and `arrival`. `preActions` and `postActions` are excluded. 
	TravelSummary VehicleSummary `json:"travelSummary,omitempty"`
	// Line string in [Flexible Polyline](https://github.com/heremaps/flexible-polyline) format
	Polyline string `json:"polyline,omitempty"`
	// Contains a list of issues related to this section of the route.  Follows a list of possible notice codes:  * `simplePolyline`: An accurate polyline is not available for this section.   The returned polyline has been generated from departure and arrival places. * `routingOptionViolated`:  This section violates a route option. This is done if honoring   the route option would result in no route at all. 
	Notices []Notice `json:"notices,omitempty"`
	// Spans attached to a `Section` describing vehicle content. 
	Spans []VehicleSpan `json:"spans,omitempty"`
	Transport VehicleTransport `json:"transport"`
}
