/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Avoid struct for Avoid
type Avoid struct {
	// A comma separated list of features that routes will avoid.  * `seasonalClosure` * `tollRoad` * `controlledAccessHighway` * `ferry` * `carShuttleTrain` * `tunnel` * `dirtRoad` * `difficultTurns` 
	Features string `json:"features,omitempty"`
	// A pipe separated list of user defined areas that routes will avoid to go through.  Format: `{shape1}|{shape2}|{shape3}...`  Supported shape format: * Bounding box - A rectangular area on earth defined by a comma separated list of two latitude and two longitude values.   - Format: `bbox:{west},{south},{east},{north}`     + `{west}`  - Longitude value of the westernmost point of the area.     + `{south}` - Latitude value of the southernmost point of the area.     + `{east}`  - Longitude value of the easternmost point of the area.     + `{north}` - Latitude value of the northernmost point of the area.   - Example: `bbox:13.082,52.416,13.628,52.626` - Bounding box of Berlin 
	Areas string `json:"areas,omitempty"`
}
