// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TransitTransport Transit transport information.
type TransitTransport struct {
	// Extensible enum: `highSpeedTrain` `intercityTrain` `interRegionalTrain` `regionalTrain` `cityTrain` `bus` `ferry` `subway` `lightRail` `privateBus` `inclined` `aerial` `busRapid` `monorail` `carShuttleTrain` `flight` `spaceship` `...`   Transit mode of transport in the route response 
	Mode string `json:"mode"`
	// Transit line name
	Name string `json:"name,omitempty"`
	// Transit line headsign
	Headsign string `json:"headsign,omitempty"`
	// Human readable transport category (such as Bus, Gondola, Tram, Train, ...)
	Category string `json:"category,omitempty"`
	// Color of the transport polyline and background for the transport name.
	Color string `json:"color,omitempty"`
	// Color of the transport name.
	TextColor string `json:"textColor,omitempty"`
}
