/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
import (
	"time"
)
// VehicleDeparture Describe a departure or an arrival location and time.
type VehicleDeparture struct {
	// Expected time of the departure of the event. Format is **RFC 3339**, section 5.6 as defined by `date-time`.
	Time time.Time `json:"time,omitempty"`
	Place VehiclePlace `json:"place"`
	// Vehicle battery charge (in kWh).
	Charge float32 `json:"charge,omitempty"`
}
