/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// BaseSummary Total value of key attributes for a route section.
type BaseSummary struct {
	// Duration in seconds
	Duration int32 `json:"duration"`
	// Distance in meters
	Length int32 `json:"length"`
}
