// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TransitSpan Contains information attached to a contiguous part of a `Section`. The information may be attached along different dimensions of a section which are geometry (spatial), distance or time.  A section, if it uses spans, has an optional attribute `spans` which is an array of extended `Span` types.  The attributes of a span which should be returned in the response are configured by a request parameter.  Use this type as a base for any span extension for sections that provide spans. 
type TransitSpan struct {
	// Offset of a coordinate in the section's polyline. 
	Offset int32 `json:"offset,omitempty"`
	// Distance in meters
	Length int32 `json:"length,omitempty"`
	// Duration in seconds
	Duration int32 `json:"duration,omitempty"`
	// ISO-3166-1 alpha-3 code
	CountryCode string `json:"countryCode,omitempty"`
	// Designated name for the span (e.g. a street name or a transport name)
	Names []LocalizedString `json:"names,omitempty"`
}
