// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// HealthResponseFailSchema Returns the health of the service
type HealthResponseFailSchema struct {
	// Health status of the service:  * `ok` - the service is operating normally * `fail` - the service is currently encountering a failure 
	Status string `json:"status,omitempty"`
}
