// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// PedestrianTransport Information about a transport
type PedestrianTransport struct {
	// Extensible enum: `pedestrian` `...`   Pedestrian mode of transport.  Since the supported pedestrian modes may be extended in the future, the pedestrian mode should be hidden when an unknown mode is encountered. 
	Mode string `json:"mode"`
}
