/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// Units Units of measurement used, for example, in guidance instructions. The default is `metric`.
type Units string

// List of Units
const (
	UNITS_METRIC Units = "metric"
	UNITS_IMPERIAL Units = "imperial"
)
