/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// DynamicSpeedInfo Describes dynamic speed information, such as traffic speed, estimated speed without traffic, and turn time. 
type DynamicSpeedInfo struct {
	// Traffic-enabled speed, which is the estimated speed considering traffic-relevant constraints. 
	TrafficSpeed float32 `json:"trafficSpeed"`
	// Estimated speed without considering any traffic-related constraints.
	BaseSpeed float32 `json:"baseSpeed"`
	// Turn time estimate considering traffic and transport mode needed for turning from this segment into the next. 
	TurnTime int32 `json:"turnTime"`
}
