// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// DataVersion Version of a specific data set
type DataVersion struct {
	// Identifies a data set, e.g. a HRN, or a service specific identifier
	Name string `json:"name"`
	// The current version of this data set
	Version string `json:"version"`
}
