// Code generated by OpenAPI Generator. DO NOT EDIT.
/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// VehicleTransport Information about a transport
type VehicleTransport struct {
	// Extensible enum: `car` `truck` `...`   Vehicle mode of transport.  Since the supported vehicle modes may be extended in the future, the vehicle mode should be hidden when an unknown mode is encountered. 
	Mode string `json:"mode"`
}
