/*
 * Routing API v8
 *
 * A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.
 *
 * API version: 8.3.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package routingv8
// TunnelCategory Specifies the tunnel category used to restrict transport of specific goods. 
type TunnelCategory string

// List of TunnelCategory
const (
	TUNNELCATEGORY_B TunnelCategory = "B"
	TUNNELCATEGORY_C TunnelCategory = "C"
	TUNNELCATEGORY_D TunnelCategory = "D"
	TUNNELCATEGORY_E TunnelCategory = "E"
)
